main: dev.gardeningtool.tokennotes.TokenNotes
name: TokenNotes
version: 1.0
author: Gardening_Tool
depend: [TokenEnchant]
description: A token BankNotes plugin
commands:
  tewithdraw: 
    description: Withdraw tokens
